# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4c40098a393dbefe6877ca62d2f366999fb92744356a463d0e5f79406a9697eceb54d70015f7c129f9a8565df63573708edbb608ab627fd6eeb8a49fd497d93f

test:
  secret_key_base: b01ce812e02978dcb328d0f33513026ff77efde9f302aaf207bd6fee6ecbf8b8b0b6af83c06277179020016abdfdd3837f1a4b51efc79e0e5fdee4954c878d89

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
